stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Instalando dependencias..."
    - npm install
  artifacts:
    paths:
      - node_modules/

unit_test:
  stage: test
  script:
    - echo "Ejecutando tests unitarios..."
    - npm run test:unit
  dependencies:
    - build_job

integration_test:
  stage: test
  script:
    - echo "Ejecutando tests de integración..."
    - npm run test:integration
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  script:
    - echo "Desplegando aplicación..."
    - npm run deploy
  only:
    - main
  when: manual
