# Ejemplo básico de .gitlab-ci.yml
stages:
  - build
  - test
  - deploy

variables:
  GIT_DEPTH: "3"

build-job:
  stage: build
  script:
    - echo "Compilando la aplicación..."
    - echo "Compilación completada."
  artifacts:
    paths:
      - build/

test-job:
  stage: test
  script:
    - echo "Ejecutando tests..."
    - echo "Tests completados exitosamente."

deploy-job:
  stage: deploy
  script:
    - echo "Desplegando aplicación..."
    - echo "Aplicación desplegada correctamente."
  only:
    - main
