stages:
  - install
  - build
  - code-quality

variables:
  SAST_EXCLUDED_ANALYZERS: "nodejs-scan-sast" # this only scans js files, doesn't work with ts

install_dependencies:
  stage: install
  image: node:22.14
  tags:
    - global
  before_script:
    - npm config --location user set "registry=https://eugit.randstadgis.com/api/v4/groups/ssc-grp-c-one/-/packages/npm/" && \
    - npm config --location user set "//eugit.randstadgis.com/api/v4/groups/ssc-grp-c-one/-/packages/npm/:_authToken=${GITLAB_ACCESS_TOKEN}"
  script:
    - npm ci
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

build:
  stage: build
  image: node:22.14
  tags:
    - global
  script:
    - npm run build:esbuild
  cache:
    paths:
      - node_modules/
      - dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

test:
  stage: code-quality
  image: node:22.14
  tags:
    - global
  script:
    - npm run test
  cache:
    paths:
      - node_modules/

lint:
  stage: code-quality
  image: node:22.14
  tags:
    - global
  script:
    - npm run lint
  cache:
    paths:
      - node_modules/

prettier:
  stage: code-quality
  image: node:22.14
  tags:
    - global
  script:
    - npm run prettier
  cache:
    paths:
      - node_modules/
check-types:
  stage: code-quality
  image: node:22.14
  tags:
    - global
  script:
    - npm run check-types
  cache:
    paths:
      - node_modules/
sast:
  stage: code-quality
  tags:
    - global
  cache:
    paths:
      - dist/
      - node_modules/
secret_detection:
  stage: code-quality
  tags:
    - global
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
