stages:
  - build

build:
  stage: build
  allow_failure: false
  only:
    - dev
    - test
    - ppr
    - prod
  tags:
    - randstad-bluex
  script:
    - git remote add codecommit /fake-temp-url || true
    - git remote set-url codecommit ssh://git-codecommit.eu-west-1.amazonaws.com-new/v1/repos/git-bluex-prd-bx-gitlab-runner
    - git push codecommit HEAD:refs/heads/$CI_COMMIT_REF_NAME
