stages:
  - build
  - pages

build_docs:
  stage: build
  script:
    - pip install mkdocs
    - mkdocs build
  artifacts:
    paths:
      - site/

pages:
  stage: pages
  dependencies:
    - build_docs
  script:
    - cp -r site/* public/
  artifacts:
    paths:
      - public
  only:
    - main
