# Ejemplo de .gitlab-ci.yml con sección include existente
stages:
  - setup
  - test
  - build
  - deploy

include:
  - local: 'ci/build-jobs.yml'
  - local: 'ci/test-jobs.yml'
  - project: 'my-group/my-project'
    file: '/templates/ci-template.yml'
    ref: main

variables:
  GIT_STRATEGY: fetch

setup-job:
  stage: setup
  script:
    - echo "Configurando el entorno..."
    - mkdir -p build

test-job:
  stage: test
  script:
    - echo "Ejecutando pruebas..."
  dependencies:
    - setup-job

build-job:
  stage: build
  script:
    - echo "Compilando el proyecto..."
  artifacts:
    paths:
      - build/

deploy-job:
  stage: deploy
  script:
    - echo "Desplegando a producción..."
  only:
    - main
  when: manual
