stages:
  - build
  - test
  - quality
  - deploy

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

unit_tests:
  stage: test
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

integration_tests:
  stage: test
  script:
    - mvn verify -DskipUnitTests
  artifacts:
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

code_quality:
  stage: quality
  script:
    - mvn sonar:sonar
  only:
    - main
    - develop

deploy_staging:
  stage: deploy
  script:
    - echo "Desplegando en entorno de staging"
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - echo "Desplegando en producción"
  environment:
    name: production
  only:
    - main
  when: manual
