stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

integration_tests:
  stage: test
  script:
    - echo "Running integration tests..."
    - npm run test:integration
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual

include:
- template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  script:
    - echo "Building application..."
    - npm run build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - ./deploy.sh prod
  environment:
    name: production
    url: https://example.com
  rules:
    - if: '$CI_COMMIT_TAG != null'
