# Ejemplo incorrecto con múltiples bloques include
stages:
  - prepare
  - build
  - test
  - deploy

include:
  - local: 'ci/dependencies.yml'

variables:
  NODE_ENV: production

prepare-job:
  stage: prepare
  script:
    - echo "Preparando dependencias..."

build-job:
  stage: build
  script:
    - echo "Compilando la aplicación..."

# Este segundo bloque include causará un error de sintaxis YAML
include:
  - local: 'ci/test-suites.yml'

test-job:
  stage: test
  script:
    - echo "Ejecutando tests unitarios..."

deploy-job:
  stage: deploy
  script:
    - echo "Desplegando a producción..."
  only:
    - main
