# Ejemplo con uno de los templates de seguridad ya incluido
stages:
  - build
  - test
  - security
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - local: 'ci/build-config.yml'

variables:
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp"
  SCAN_KUBERNETES_MANIFESTS: "true"

build-job:
  stage: build
  script:
    - echo "Compilando la aplicación..."
  artifacts:
    paths:
      - dist/

test-job:
  stage: test
  script:
    - echo "Ejecutando tests..."

deploy-job:
  stage: deploy
  script:
    - echo "Desplegando aplicación..."
  only:
    - main
