stages:
  - build
  - review
  - staging
  - production

build_docker:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

review_app:
  stage: review
  script:
    - kubectl apply -f k8s/review.yaml
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://review-$CI_COMMIT_REF_SLUG.example.com
  only:
    - branches
  except:
    - main

deploy_staging:
  stage: staging
  script:
    - kubectl apply -f k8s/staging.yaml
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - main

deploy_production:
  stage: production
  script:
    - kubectl apply -f k8s/production.yaml
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - main
