# Ejemplo 1: Pipeline simple con build y deploy
stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Compilando la aplicación..."
    - make build
  artifacts:
    paths:
      - build/

deploy_job:
  stage: deploy
  script:
    - echo "Desplegando aplicación en producción..."
    - rsync -avz build/ user@server:/path/to/deployment/
  only:
    - main
