stages:
  - install
  - verify

default:
  image: node:20.11.1
  cache:
    paths:
      - node_modules/
  tags:
    - global

variables:
  CERT_FILENAME: 'ZscalerRootCertificate-2048-SHA256.crt'
  CERT_PATH: '/etc/gitlab-runner/certs/ZscalerRootCertificate-2048-SHA256.crt'
  SYSTEM_CERTS_PATH: '/usr/local/share/ca-certificates'

install:
  stage: install
  script:
    - |
      echo "Installing ca-certificate tool"
      apt-get update && apt-get install -y ca-certificates
    - |
      echo "Setting up Zscaler certificate..."
      cp $CERT_PATH $SYSTEM_CERTS_PATH
      update-ca-certificates
      export NODE_EXTRA_CA_CERTS="$SYSTEM_CERTS_PATH/$CERT_FILENAME"
      export SSL_CERT_FILE="$SYSTEM_CERTS_PATH/$CERT_FILENAME"
    - |
      echo "Configuring .npmrc for REL Private Registry"
      npm set @rel:registry=https://${REL_GITLAB_REG}/
      npm set //${REL_GITLAB_REG}/:_authToken="${REL_GITLAB_AUTH_TOKEN}"
    - |
      echo "Running installation of packages..."
      npm install --frozen-lockfile
  only:
    - merge_requests

lint:
  stage: verify
  script:
    - npm run lint
  only:
    - merge_requests

format-check:
  stage: verify
  script:
    - npm run format:check
  only:
    - merge_requests

typescript:
  stage: verify
  script:
    - npm run compile
  only:
    - merge_requests

tests:
  stage: verify
  script:
    - npm run test
  only:
    - merge_requests
