stages:
  - test
  - install
  - build
  - publish

# Install dependencies
install_dependencies:
  stage: install
  image: node:20.11.1
  tags:
    - global
  before_script:
    - echo "@cone:registry=https://eugit.randstadgis.com/api/v4/groups/ssc-grp-c-one/-/packages/npm/" > .npmrc
    - echo "//eugit.randstadgis.com/api/v4/groups/ssc-grp-c-one/-/packages/npm/:_authToken=${GITLAB_ACCESS_TOKEN}" >> .npmrc
  script:
    - yarn ci
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

build:
  stage: build
  image: node:20.11.1
  tags:
    - global
  script:
    - yarn build
  cache:
    paths:
      - node_modules/
      - dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

# Publish the npm package
publish:
  stage: publish
  image: node:20.11.1
  tags:
    - global
  script:
    - echo "@cone:registry=$NPM_REGISTRY" > .npmrc
    - echo "//eugit.randstadgis.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - curl -I $NPM_REGISTRY
    - npm publish
  only:
    - main
  allow_failure: false
  cache:
    paths:
      - build/
      - node_modules/
