stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  script:
    - yarn lint

unit_test:
  stage: test
  script:
    - yarn test:unit
  artifacts:
    reports:
      junit: junit.xml

e2e_test:
  stage: test
  script:
    - yarn test:e2e
  artifacts:
    paths:
      - cypress/screenshots/
      - cypress/videos/

build_app:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - main
    - develop

deploy_to_staging:
  stage: deploy
  script:
    - echo "Desplegando en staging..."
  environment:
    name: staging
  only:
    - develop

deploy_to_production:
  stage: deploy
  script:
    - echo "Desplegando en producción..."
  environment:
    name: production
  only:
    - main
  when: manual


include:
